use lazy_static::lazy_static;
use serde::{Deserialize, Serialize};

/// 残局题目
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Puzzle {
    pub id: u32,
    pub name: String,
    pub difficulty: PuzzleDifficulty,
    pub description: String,
    /// 初始棋盘状态，格式：[(row, col, "Black"/"White"), ...]
    pub initial_stones: Vec<(usize, usize, String)>,
    /// 玩家执子颜色
    pub player_stone: String,
    /// 正确答案序列（可能有多个正确走法）
    pub solutions: Vec<Vec<(usize, usize)>>,
    /// 提示
    pub hint: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, PartialOrd, Ord)]
pub enum PuzzleDifficulty {
    Easy,
    Medium,
    Hard,
    Expert,
    Master,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PuzzleListItem {
    pub id: u32,
    pub name: String,
    pub difficulty: PuzzleDifficulty,
    pub description: String,
}

// 使用 lazy_static 缓存题库，避免每次调用都重新创建
lazy_static! {
    static ref ALL_PUZZLES: Vec<Puzzle> = create_all_puzzles();
}

/// 获取所有残局列表（按难度和ID排序）
#[tauri::command]
pub fn get_puzzle_list() -> Vec<PuzzleListItem> {
    let mut puzzles: Vec<PuzzleListItem> = ALL_PUZZLES
        .iter()
        .map(|p| PuzzleListItem {
            id: p.id,
            name: p.name.clone(),
            difficulty: p.difficulty,
            description: p.description.clone(),
        })
        .collect();

    // 按难度排序，同难度按 ID 排序
    puzzles.sort_by(|a, b| {
        match a.difficulty.cmp(&b.difficulty) {
            std::cmp::Ordering::Equal => a.id.cmp(&b.id),
            other => other,
        }
    });

    puzzles
}

/// 获取指定残局详情
#[tauri::command]
pub fn get_puzzle(id: u32) -> Option<Puzzle> {
    ALL_PUZZLES.iter().find(|p| p.id == id).cloned()
}

/// 检查走法是否正确
#[tauri::command]
pub fn check_puzzle_move(id: u32, moves: Vec<(usize, usize)>) -> PuzzleCheckResult {
    let puzzle = match ALL_PUZZLES.iter().find(|p| p.id == id) {
        Some(p) => p,
        None => {
            return PuzzleCheckResult {
                correct: false,
                complete: false,
                message: "题目不存在".to_string(),
            }
        }
    };

    // 检查是否匹配任一解法
    for solution in &puzzle.solutions {
        if moves.len() <= solution.len() {
            let matches = moves
                .iter()
                .zip(solution.iter())
                .all(|(m, s)| m.0 == s.0 && m.1 == s.1);
            if matches {
                if moves.len() == solution.len() {
                    return PuzzleCheckResult {
                        correct: true,
                        complete: true,
                        message: "恭喜！完成残局！".to_string(),
                    };
                } else {
                    return PuzzleCheckResult {
                        correct: true,
                        complete: false,
                        message: "正确，继续！".to_string(),
                    };
                }
            }
        }
    }

    PuzzleCheckResult {
        correct: false,
        complete: false,
        message: "走法不正确，请重试".to_string(),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PuzzleCheckResult {
    pub correct: bool,
    pub complete: bool,
    pub message: String,
}

/// 内置残局题库（仅在初始化时调用一次）
fn create_all_puzzles() -> Vec<Puzzle> {
    vec![
        // 简单难度 - 直接连五
        Puzzle {
            id: 1,
            name: "直接连五".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "黑棋一步连五获胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (7, 9, "Black".to_string()),
                (7, 10, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (8, 9, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 11)], vec![(7, 6)]],
            hint: "找到能直接连成五子的位置".to_string(),
        },
        Puzzle {
            id: 2,
            name: "斜线连五".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "黑棋斜线连五".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 9, "Black".to_string()),
                (10, 10, "Black".to_string()),
                (6, 7, "White".to_string()),
                (7, 8, "White".to_string()),
                (8, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(6, 6)], vec![(11, 11)]],
            hint: "观察斜线方向".to_string(),
        },
        Puzzle {
            id: 3,
            name: "防守反击".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "白棋一步连五".to_string(),
            initial_stones: vec![
                (7, 5, "White".to_string()),
                (7, 6, "White".to_string()),
                (7, 7, "White".to_string()),
                (7, 8, "White".to_string()),
                (6, 5, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (6, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(7, 9)], vec![(7, 4)]],
            hint: "白棋已有四子连线".to_string(),
        },
        // 中等难度 - 活四/冲四
        Puzzle {
            id: 4,
            name: "活四必胜".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋形成活四获胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 9, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 9, "White".to_string()),
                (8, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 8)]],
            hint: "在中间位置落子形成活四".to_string(),
        },
        Puzzle {
            id: 5,
            name: "双冲四".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋形成双冲四必胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 9, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (7, 9, "Black".to_string()),
                (6, 6, "White".to_string()),
                (10, 10, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 10, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 10)]],
            hint: "找到同时形成两个冲四的位置".to_string(),
        },
        Puzzle {
            id: 6,
            name: "冲四活三".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋冲四活三必胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (7, 9, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 8, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 10, "White".to_string()),
                (10, 8, "White".to_string()),
                (7, 11, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 10)]],
            hint: "同时形成冲四和活三".to_string(),
        },
        Puzzle {
            id: 7,
            name: "活三进攻".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋形成活三迫使白棋防守".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 9, "White".to_string()),
                (9, 9, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9)]],
            hint: "形成活三的同时连接棋子".to_string(),
        },
        // 困难难度 - 多步杀棋
        Puzzle {
            id: 8,
            name: "三步杀".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋三步内获胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 8, "White".to_string()),
                (9, 7, "White".to_string()),
                (9, 9, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9), (8, 8)]],
            hint: "先形成活三，再连续进攻".to_string(),
        },
        Puzzle {
            id: 9,
            name: "VCF进攻".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 9, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (7, 9, "White".to_string()),
                (10, 10, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 8), (7, 4)]],
            hint: "利用冲四迫使对手防守，再找下一个冲四点".to_string(),
        },
        Puzzle {
            id: 10,
            name: "复杂局面".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋找到必胜走法".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 6, "White".to_string()),
                (8, 8, "White".to_string()),
                (9, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9), (6, 6)]],
            hint: "观察多个方向的进攻可能".to_string(),
        },
        Puzzle {
            id: 11,
            name: "绝杀局".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "白棋必胜局面".to_string(),
            initial_stones: vec![
                (7, 6, "White".to_string()),
                (7, 7, "White".to_string()),
                (7, 8, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 7, "White".to_string()),
                (6, 6, "Black".to_string()),
                (6, 7, "Black".to_string()),
                (6, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (7, 10, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(7, 9), (10, 7)]],
            hint: "白棋有两个方向的进攻".to_string(),
        },
        Puzzle {
            id: 12,
            name: "防守中的进攻".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "在防守的同时寻找进攻机会".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (7, 9, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (6, 7, "White".to_string()),
                (7, 8, "White".to_string()),
                (8, 8, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(9, 9), (6, 9)]],
            hint: "利用对手的弱点反击".to_string(),
        },
        // ========== 简单难度扩展（id: 13-17）- 直接连五 ==========
        Puzzle {
            id: 13,
            name: "横线连五".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "黑棋横线连五获胜".to_string(),
            initial_stones: vec![
                (6, 5, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (6, 7, "Black".to_string()),
                (6, 8, "Black".to_string()),
                (5, 5, "White".to_string()),
                (5, 6, "White".to_string()),
                (7, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(6, 9)], vec![(6, 4)]],
            hint: "在横线上找到连五位置".to_string(),
        },
        Puzzle {
            id: 14,
            name: "双线杀".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "黑棋双线连五".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (7, 9, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (5, 5, "Black".to_string()),
                (8, 10, "White".to_string()),
                (6, 10, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 10)], vec![(7, 5)], vec![(4, 4)], vec![(9, 11)]],
            hint: "有多条线路可以选择".to_string(),
        },
        Puzzle {
            id: 15,
            name: "白棋反杀".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "白棋一步连五".to_string(),
            initial_stones: vec![
                (8, 5, "White".to_string()),
                (8, 6, "White".to_string()),
                (8, 7, "White".to_string()),
                (8, 8, "White".to_string()),
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (9, 7, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(8, 9)], vec![(8, 4)]],
            hint: "白棋已有四子连线".to_string(),
        },
        Puzzle {
            id: 16,
            name: "斜线杀".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "白棋斜线连五".to_string(),
            initial_stones: vec![
                (5, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (7, 7, "White".to_string()),
                (8, 8, "White".to_string()),
                (6, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 8, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(9, 9)], vec![(4, 4)]],
            hint: "观察斜线方向".to_string(),
        },
        Puzzle {
            id: 17,
            name: "边线连五".to_string(),
            difficulty: PuzzleDifficulty::Easy,
            description: "黑棋边线连五".to_string(),
            initial_stones: vec![
                (3, 3, "Black".to_string()),
                (4, 4, "Black".to_string()),
                (5, 5, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (3, 4, "White".to_string()),
                (4, 5, "White".to_string()),
                (5, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 7)], vec![(2, 2)]],
            hint: "在边线寻找连五机会".to_string(),
        },
        // ========== 中等难度扩展（id: 18-25）- 活四/冲四 ==========
        Puzzle {
            id: 18,
            name: "跳活四".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋形成跳活四获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (7, 10, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 9, "White".to_string()),
                (8, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9)], vec![(7, 7)]],
            hint: "在空位落子形成跳活四".to_string(),
        },
        Puzzle {
            id: 19,
            name: "四三杀".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋四三必胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9)]],
            hint: "同时形成冲四和活三".to_string(),
        },
        Puzzle {
            id: 20,
            name: "双三必胜".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋双活三必胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (9, 9, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 9, "White".to_string()),
                (9, 7, "White".to_string()),
                (7, 10, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9)]],
            hint: "一手棋形成两个活三".to_string(),
        },
        Puzzle {
            id: 21,
            name: "冲四防杀".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋冲四同时防守".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 6, "White".to_string()),
                (9, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(5, 5)], vec![(9, 8)]],
            hint: "冲四的同时阻止白棋".to_string(),
        },
        Puzzle {
            id: 22,
            name: "连四活三".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋连四活三必胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9)]],
            hint: "利用连四和活三组合".to_string(),
        },
        Puzzle {
            id: 23,
            name: "跳四三".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋跳四三必胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 8, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 9, "White".to_string()),
                (10, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9)]],
            hint: "跳冲四和活三组合".to_string(),
        },
        Puzzle {
            id: 24,
            name: "白棋四三".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "白棋四三必胜".to_string(),
            initial_stones: vec![
                (7, 6, "White".to_string()),
                (7, 7, "White".to_string()),
                (7, 8, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 7, "White".to_string()),
                (6, 6, "Black".to_string()),
                (6, 8, "Black".to_string()),
                (6, 9, "Black".to_string()),
                (10, 7, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(7, 9)]],
            hint: "白棋四三杀棋".to_string(),
        },
        Puzzle {
            id: 25,
            name: "连环杀".to_string(),
            difficulty: PuzzleDifficulty::Medium,
            description: "黑棋连环进攻".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 8, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 9, "White".to_string()),
                (10, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(10, 9)], vec![(6, 7)]],
            hint: "创造多个威胁点".to_string(),
        },
        // ========== 困难难度扩展（id: 26-35）- 2-3步杀棋 ==========
        Puzzle {
            id: 26,
            name: "连续冲四".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 8), (7, 4)]],
            hint: "先冲四，再找下一个冲四点".to_string(),
        },
        Puzzle {
            id: 27,
            name: "双线VCF".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋双线连续冲四".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (9, 8, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 10, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 9), (8, 8)]],
            hint: "利用两个方向的冲四".to_string(),
        },
        Puzzle {
            id: 28,
            name: "精妙VCF".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋三步VCF获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 8, "White".to_string()),
                (8, 5, "White".to_string()),
                (8, 6, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 8), (7, 4), (6, 4)]],
            hint: "连续三次冲四获胜".to_string(),
        },
        Puzzle {
            id: 29,
            name: "防守反击VCF".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋防守后VCF获胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 6, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(9, 8), (10, 9)]],
            hint: "先防守再连续冲四".to_string(),
        },
        Puzzle {
            id: 30,
            name: "复杂VCF".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋复杂VCF序列".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 9, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(8, 7), (7, 5)]],
            hint: "找到关键的冲四点".to_string(),
        },
        Puzzle {
            id: 31,
            name: "白棋VCF".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "白棋连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 5, "White".to_string()),
                (7, 6, "White".to_string()),
                (7, 7, "White".to_string()),
                (8, 6, "White".to_string()),
                (8, 8, "White".to_string()),
                (9, 5, "White".to_string()),
                (6, 5, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (6, 8, "Black".to_string()),
                (8, 5, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (10, 8, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(7, 8), (7, 4)]],
            hint: "白棋连续冲四".to_string(),
        },
        Puzzle {
            id: 32,
            name: "三三杀".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋三三必胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 5, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(6, 6), (10, 8)]],
            hint: "同时形成两个活三".to_string(),
        },
        Puzzle {
            id: 33,
            name: "四四杀".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋双四必胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 9, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 5), (6, 5)]],
            hint: "形成两个冲四".to_string(),
        },
        Puzzle {
            id: 34,
            name: "陷阱杀".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋设陷阱获胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (9, 9, "Black".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 6, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(9, 8), (8, 9)]],
            hint: "布下陷阱让对手无法防守".to_string(),
        },
        Puzzle {
            id: 35,
            name: "绝妙反击".to_string(),
            difficulty: PuzzleDifficulty::Hard,
            description: "黑棋防守反击获胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 7, "White".to_string()),
                (8, 6, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(10, 7), (10, 6)]],
            hint: "防守同时创造杀机".to_string(),
        },
        // ========== Expert难度（id: 36-45）- 3-4步杀棋 ==========
        Puzzle {
            id: 36,
            name: "三连VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋三次连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 8, "White".to_string()),
                (8, 5, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 8), (7, 4), (6, 4)]],
            hint: "连续三次冲四，每次都迫使对手防守".to_string(),
        },
        Puzzle {
            id: 37,
            name: "双活三VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋双活三转VCF获胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 9, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 5), (8, 8), (6, 5)]],
            hint: "先形成双活三，再转VCF".to_string(),
        },
        Puzzle {
            id: 38,
            name: "防守反击VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋防守反击VCF获胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 5, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(10, 6), (10, 7), (10, 8)]],
            hint: "防守点同时也是进攻起点".to_string(),
        },
        Puzzle {
            id: 39,
            name: "四步VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋四次连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 4, "Black".to_string()),
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (8, 5, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 4, "Black".to_string()),
                (6, 4, "White".to_string()),
                (6, 5, "White".to_string()),
                (6, 7, "White".to_string()),
                (7, 7, "White".to_string()),
                (8, 4, "White".to_string()),
                (8, 6, "White".to_string()),
                (9, 5, "White".to_string()),
                (9, 6, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 3), (7, 2), (7, 8), (6, 3)]],
            hint: "连续四次冲四，精确计算每一步".to_string(),
        },
        Puzzle {
            id: 40,
            name: "白棋三连VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "白棋三次连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 5, "White".to_string()),
                (7, 6, "White".to_string()),
                (7, 7, "White".to_string()),
                (8, 6, "White".to_string()),
                (8, 8, "White".to_string()),
                (9, 5, "White".to_string()),
                (6, 5, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (6, 8, "Black".to_string()),
                (8, 5, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (10, 8, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(7, 8), (7, 4), (6, 4)]],
            hint: "白棋连续三次冲四".to_string(),
        },
        Puzzle {
            id: 41,
            name: "多线VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋多线VCF获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 8, "White".to_string()),
                (9, 5, "White".to_string()),
                (9, 6, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(8, 7), (7, 4), (6, 4)]],
            hint: "利用多个方向的冲四组合".to_string(),
        },
        Puzzle {
            id: 42,
            name: "精妙防守".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋精妙防守后VCF获胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 7, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(9, 9), (10, 10), (10, 9)]],
            hint: "找到既是防守又是进攻的关键点".to_string(),
        },
        Puzzle {
            id: 43,
            name: "陷阱VCF".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋设陷阱后VCF获胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (8, 9, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (9, 8, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 6, "White".to_string()),
                (8, 8, "White".to_string()),
                (9, 6, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(10, 8), (10, 9), (10, 6)]],
            hint: "布下陷阱，让对手陷入被动".to_string(),
        },
        Puzzle {
            id: 44,
            name: "复杂杀局".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋复杂多步杀棋".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 8, "White".to_string()),
                (8, 5, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 4), (10, 6), (10, 5)]],
            hint: "灵活运用多种进攻手段".to_string(),
        },
        Puzzle {
            id: 45,
            name: "绝妙反击".to_string(),
            difficulty: PuzzleDifficulty::Expert,
            description: "黑棋绝妙反击VCF获胜".to_string(),
            initial_stones: vec![
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 8, "White".to_string()),
                (9, 9, "White".to_string()),
                (10, 6, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(10, 8), (10, 9), (11, 10)]],
            hint: "在看似防守的棋子中隐藏杀机".to_string(),
        },
        // ========== Master难度（id: 46-50）- 4-6步+杀棋 ==========
        Puzzle {
            id: 46,
            name: "五连VCF".to_string(),
            difficulty: PuzzleDifficulty::Master,
            description: "黑棋五次连续冲四获胜".to_string(),
            initial_stones: vec![
                (7, 3, "Black".to_string()),
                (7, 4, "Black".to_string()),
                (7, 5, "Black".to_string()),
                (8, 4, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (9, 3, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (6, 3, "White".to_string()),
                (6, 4, "White".to_string()),
                (6, 6, "White".to_string()),
                (7, 6, "White".to_string()),
                (8, 3, "White".to_string()),
                (8, 5, "White".to_string()),
                (9, 4, "White".to_string()),
                (9, 6, "White".to_string()),
                (10, 3, "White".to_string()),
                (10, 5, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 2), (7, 7), (6, 2), (7, 8), (6, 7)]],
            hint: "连续五次冲四，需要精确计算每一步".to_string(),
        },
        Puzzle {
            id: 47,
            name: "多线进攻".to_string(),
            difficulty: PuzzleDifficulty::Master,
            description: "黑棋多线进攻获胜".to_string(),
            initial_stones: vec![
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 5, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 5, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (7, 8, "White".to_string()),
                (8, 6, "White".to_string()),
                (8, 8, "White".to_string()),
                (9, 7, "White".to_string()),
                (9, 8, "White".to_string()),
                (10, 5, "White".to_string()),
                (10, 6, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(9, 4), (10, 4), (8, 4), (7, 4), (6, 4)]],
            hint: "同时准备多个方向的进攻".to_string(),
        },
        Puzzle {
            id: 48,
            name: "弱手杀".to_string(),
            difficulty: PuzzleDifficulty::Master,
            description: "黑棋弱手起手获胜".to_string(),
            initial_stones: vec![
                (7, 6, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (7, 8, "Black".to_string()),
                (8, 6, "Black".to_string()),
                (8, 8, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (6, 8, "White".to_string()),
                (6, 9, "White".to_string()),
                (7, 9, "White".to_string()),
                (8, 7, "White".to_string()),
                (9, 6, "White".to_string()),
                (9, 8, "White".to_string()),
                (9, 9, "White".to_string()),
                (10, 6, "White".to_string()),
                (10, 7, "White".to_string()),
                (10, 8, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(10, 9), (10, 10), (11, 11), (11, 10), (10, 5)]],
            hint: "看似无关的一手，实则是获胜关键".to_string(),
        },
        Puzzle {
            id: 49,
            name: "白棋长杀".to_string(),
            difficulty: PuzzleDifficulty::Master,
            description: "白棋长序列杀棋获胜".to_string(),
            initial_stones: vec![
                (7, 4, "White".to_string()),
                (7, 5, "White".to_string()),
                (7, 6, "White".to_string()),
                (8, 4, "White".to_string()),
                (8, 6, "White".to_string()),
                (9, 4, "White".to_string()),
                (9, 5, "White".to_string()),
                (6, 4, "Black".to_string()),
                (6, 5, "Black".to_string()),
                (6, 6, "Black".to_string()),
                (6, 7, "Black".to_string()),
                (7, 7, "Black".to_string()),
                (8, 5, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (9, 7, "Black".to_string()),
                (10, 4, "Black".to_string()),
                (10, 5, "Black".to_string()),
                (10, 6, "Black".to_string()),
            ],
            player_stone: "White".to_string(),
            solutions: vec![vec![(7, 3), (8, 3), (9, 3), (10, 3), (6, 3)]],
            hint: "白棋长序列进攻，需要深谋远虑".to_string(),
        },
        Puzzle {
            id: 50,
            name: "终极挑战".to_string(),
            difficulty: PuzzleDifficulty::Master,
            description: "黑棋终极杀棋挑战".to_string(),
            initial_stones: vec![
                (7, 4, "Black".to_string()),
                (7, 5, "Black".to_string()),
                (7, 6, "Black".to_string()),
                (8, 5, "Black".to_string()),
                (8, 7, "Black".to_string()),
                (9, 4, "Black".to_string()),
                (9, 6, "Black".to_string()),
                (6, 4, "White".to_string()),
                (6, 5, "White".to_string()),
                (6, 6, "White".to_string()),
                (6, 7, "White".to_string()),
                (7, 7, "White".to_string()),
                (8, 4, "White".to_string()),
                (8, 6, "White".to_string()),
                (9, 5, "White".to_string()),
                (9, 7, "White".to_string()),
                (10, 4, "White".to_string()),
                (10, 5, "White".to_string()),
                (10, 6, "White".to_string()),
                (10, 7, "White".to_string()),
            ],
            player_stone: "Black".to_string(),
            solutions: vec![vec![(7, 3), (11, 7), (10, 8), (9, 8), (8, 8), (6, 3)]],
            hint: "终极挑战，需要运用所有技巧".to_string(),
        },
    ]
}
